namespace EInvoiceQuickBooks.Models
{
    public class DBInvoice
    {
        public int? Id { get; set; }
        public int? TaxOfficeSchedulerId { get; set; }
        public int? ParticipantId { get; set; }
        public string? ParticipantName { get; set; }
        public string? SourceFileName { get; set; }
        public string? EInvoiceNumber { get; set; }
        public string? SourceName { get; set; }
        public string? OutputFormat { get; set; }
        public string? Mode { get; set; }
        public string? Status { get; set; }
        public string? CacPostalSellerAddress { get; set; }
        public string? CbcIdentificationCode { get; set; }
        public string? CbcSellerCompanyID { get; set; }
        public string? CbcInvoiceTypeCode { get; set; }
        public string? CbcIssueDate { get; set; }
        public string? CbcLineExtensionAmount { get; set; }
        public string? CbcSellerName { get; set; }
        public string? CbcBuyerName { get; set; }
        public string? CbcNameDeliverToPartyName { get; set; }
        public string? CbcBuyerCompanyID { get; set; }
        public string? ValidationLink { get; set; }
        public string? CacPostalBuyerAddress { get; set; }
        public string? CbcSellerVATID { get; set; }
        public string? CbcBuyerVATID { get; set; }
        public string? CbcCompanyLegalForm { get; set; }
        public string? CbcDescription { get; set; }
        public string? CacPrice { get; set; }
        public string? CacTaxTotal { get; set; }
        public string? EInvoiceType { get; set; }
        public int? ETemplateId { get; set; }
        public int? TemplateId { get; set; }
        public string? TaxId { get; set; }
        public string? RegnNo { get; set; }
        public string? SstRegnNo { get; set; }
        public string? Email { get; set; }
        public string? Phone { get; set; }
        public DateTime? EInvoiceDateTime { get; set; }
        public string? AddressLine1 { get; set; }
        public string? AddressLine2 { get; set; }
        public string? CacInvoicePeriod { get; set; }
        public string? CurrencyCode { get; set; }
        public string? InvoiceValidator { get; set; }
        public string? TaxOfficeSubmitter { get; set; }
        public string? CbcPrecedingInvoicenumber { get; set; }
        public string? CbcIDPaymentAccountIdentifier { get; set; }
        public string? CacPaymentTerms { get; set; }
        public string? CacAddress { get; set; }
        public string? CbcIDInvoiceNumber { get; set; }
        public string? CbcSellerElectronicMail { get; set; }
        public string? CbcBuyerElectronicMail { get; set; }
        public string? CbcBuyerReference { get; set; }
        public string? CbcDocumentCurrencyCode { get; set; }
        public string? CbcTaxCurrencyCode { get; set; }
        public string? CbcPayableAmount { get; set; }
        public string? CbcPaymentID { get; set; }
        public string? CbcPercent { get; set; }
        public string? CbcSellerRegnName { get; set; }
        public string? CbcBuyerRegnName { get; set; }
        public string? CbcTaxableAmount { get; set; }
        public string? CbcTaxExclusiveAmount { get; set; }
        public string? CbcTaxExemptionReason { get; set; }
        public string? CbcTaxInclusiveAmount { get; set; }
        public string? CbcTaxPointDate { get; set; }
        public string? CbcSellerTelephone { get; set; }
        public string? CbcBuyerTelephone { get; set; }
        public string? CbcBusinessActivityDesc { get; set; }
        public string? TotalAllowanceAmount { get; set; }
        public string? TotalTaxAmount { get; set; }
        public string? TotalAmountDue { get; set; }
        public string? PrePaidAmount { get; set; }
        public string? CbcPaidDate { get; set; }
        public string? CbcPaidTime { get; set; }
        public string? CbcPaidId { get; set; }
        public string? PayableRoundingAmount { get; set; }
        public string? TotalChangeAmount { get; set; }
        public string? TotalLineAmount { get; set; }
        public string? CbcMSICCode { get; set; }
        public DateTime? CbcIRBMValidationDate { get; set; }
        public string? NamePaymentMeansText { get; set; }
        public string? IrbmUniqueNo { get; set; }
        public string? SchemeID { get; set; }
        public string? UnitCode { get; set; }
        public string? CbcPaymentCurrencyCode { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CbcNote { get; set; }
        public string? PdfBlob { get; set; }
        public string? PdfXml { get; set; }
        public string? XmlWithQRBlob { get; set; }
        public string? PdfWithQRBlob { get; set; }
        public string? JsonInvoiceBlob { get; set; }
        public string? JsonWithQRBlob { get; set; }
        public string? WorkflowStatus { get; set; }
        public string? InvoiceVersion { get; set; }
        public string? CbcSellerSSTRegistrationNumber { get; set; }
        public string? CbcSellerTourismTaxRegistrationNumber { get; set; }
        public string? CbcSStreetName { get; set; }
        public string? CbcSAdditionalStreetName1 { get; set; }
        public string? CbcSAdditionalStreetName2 { get; set; }
        public string? CbcSPostalZone { get; set; }
        public string? CbcSCityName { get; set; }
        public string? CbcSCountrySubentity { get; set; }
        public string? CbcSCountryIdentificationCode { get; set; }
        public string? CbcBStreetName { get; set; }
        public string? CbcBAdditionalStreetName1 { get; set; }
        public string? CbcBAdditionalStreetName2 { get; set; }
        public string? CbcBPostalZone { get; set; }
        public string? CbcBCityName { get; set; }
        public string? CbcBCountrySubentity { get; set; }
        public string? CbcBCountryIdentificationCode { get; set; }
        public string? CbcBSSTRegistrationNumber { get; set; }
        public string? CbcDStreetName { get; set; }
        public string? CbcDAdditionalStreetName1 { get; set; }
        public string? CbcDAdditionalStreetName2 { get; set; }
        public string? CbcDPostalZone { get; set; }
        public string? CbcDCityName { get; set; }
        public string? CbcDCountrySubentity { get; set; }
        public string? CbcDCountryIdentificationCode { get; set; }
        public string? CbcShipRecipientName { get; set; }
        public string? CbcShipRecipientVATID { get; set; }
        public string? CbcShipRecipientCompanyID { get; set; }
        public string? CbcShipRecipientStreetName { get; set; }
        public string? CbcShipRecipientAdditionalStreetName1 { get; set; }
        public string? CbcShipRecipientAdditionalStreetName2 { get; set; }
        public string? CbcShipRecipientPostalZone { get; set; }
        public string? CbcShipRecipientCityName { get; set; }
        public string? CbcShipRecipientCountrySubentity { get; set; }
        public string? CbcShipRecipientCountryIdentificationCode { get; set; }
        public string? CbcCalculationRate { get; set; }
        public DateTime? CbcStartDate { get; set; }
        public DateTime? CbcEndDate { get; set; }
        public DateTime? ValidityEndDateTime { get; set; }
        public int? RemainingHours { get; set; }
        public string? CbcSCategory { get; set; }
        public string? CbcSSubCategory { get; set; }
        public string? CbcSBRNNumber { get; set; }
        public string? CbcSNRIC { get; set; }
        public string? CbcBCategory { get; set; }
        public string? CbcBSubCategory { get; set; }
        public string? CbcBBRNNumber { get; set; }
        public string? CbcBNRIC { get; set; }
        public string? CbcShipRecipientCategory { get; set; }
        public string? CbcShipRecipientSubCategory { get; set; }
        public string? CbcShipRecipientBRNNumber { get; set; }
        public string? CbcShipRecipientNRIC { get; set; }
        public string? CbcItemClassificationCodeClass { get; set; }
        public string? ItemClassificationCodeName { get; set; }
    }
}
